build: false

os: Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - MINICONDA: C:\xtensor-conda

init:
  - "ECHO %MINICONDA%"
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%
  - ps: if($env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
  - ps: if($env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
  - cmd: C:\Miniconda.exe /S /D=C:\xtensor-conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"
  # To enable RDP
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  # CXX14 unnecessary with MSVC
  # Also cannot be set because R uses its compile-time settings.
  - ps: sed -i 's|CXX_STD = CXX14||' R-package/src/Makevars.win
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Testing
  - conda install r r-rcpp r-base r-devtools -c conda-forge
  - conda install m2w64-gcc m2w64-make m2w64-toolchain m2-libbz2 posix
  - conda install xtensor==0.15.1 -c conda-forge
  - R -e "install.packages('RInside', repos='http://cran.us.r-project.org')"
  - mkdir build
  - cd build
  # Install miktex
  - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe appveyor DownloadFile http://mirrors.ctan.org/systems/win32/miktex/setup/miktex-portable.exe
  - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe 7z x miktex-portable.exe -oC:\miktex >NUL
  - set "PATH=%PATH%;c:\miktex\texmfs\install\miktex\bin"
  # Enable installing miktex  packages on the fly
  - initexmf --set-config-value [MPM]AutoInstall=1
  # Full build on x64 with msys64
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set R_HOME=%MINICONDA%\\R
  - set MINGW_PATH=%MINICONDA%\\Library\\mingw-w64\\bin
  - "set PATH=%PATH%;%MINGW_PATH%;%MINICONDA%\\R\\library\\RInside\\libs\\x64;%MINICONDA%\\R\\bin\\x64"
  - appveyor DownloadFile https://cran.r-project.org/bin/windows/Rtools/Rtools34.exe
  - Rtools34.exe /VERYSILENT -NoNewWindow -Wait
  - cmake -D XTENSOR_INSTALL_R_PACKAGES=OFF -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=%MINGW_PATH% -D CMAKE_INSTALL_PREFIX=%MINICONDA%\\Library -DDOWNLOAD_GTEST=ON ..
  - cmake --build . --target test_xtensor_r
  - cmake --build . --target install
  - cmake --build . --target cran
  - cd test

build_script:
  - .\test_xtensor_r
  - cd ..
  - R CMD check --as-cran .\xtensor_*.tar.gz

# To enable RDP
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
