language: cpp
dist: trusty
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8
      compiler: clang
  allow_failures:
    - compiler: clang
env:
  global:
    - MINCONDA_VERSION="4.3.21"
    - MINCONDA_LINUX="Linux-x86_64"
    - MINCONDA_OSX="MacOSX-x86_64"
before_install:
    - |
      # Configure build variables
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export PYTHONHOME=$HOME/miniconda;
      fi

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install -y texlive-latex-base texlive-latex-recommended texinfo texlive-fonts-extra texlive-fonts-recommended;
      fi

install:
    # Define the version of miniconda to download
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINCONDA_OS=$MINCONDA_LINUX;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        MINCONDA_OS=$MINCONDA_OSX;
      fi
    - if [[ "$PY" == "3" ]]; then
          wget "http://repo.continuum.io/miniconda/Miniconda3-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
      else
          wget "http://repo.continuum.io/miniconda/Miniconda2-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Host dependencies
    - conda install r r-rcpp xtensor==0.20.4 -c conda-forge
    # Build dependencies
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        conda install gxx_linux-64 -c conda-forge;
      fi
    - conda install cmake -c conda-forge
    # Test dependencies
    - conda install r-rinside r-devtools r-testthat -c conda-forge
    # Activate root environment
    - source activate root
    # Build
    - mkdir build
    - cd build
    - cmake -D DOWNLOAD_GTEST=ON -D CMAKE_INSTALL_PREFIX=$HOME/miniconda -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
    - cmake --build . --target test_xtensor_r
    - cmake --build . --target install
    # Install R package
    - export TAR="/bin/tar"
    - R -e "library(devtools); install_github('QuantStack/Xtensor.R', configure.args = '--novendor')"

script:
    # Run C++ tests
    - cd test
    - ./test_xtensor_r
    # Run R package tests
    - mkdir ~/.R
    - touch ~/.R/Makevars
    - echo "CXX14=$CXX" >> ~/.R/Makevars
    - echo "CXX14FLAGS=-fPIC -O2" >> ~/.R/Makevars
    - cd ../../test
    - Rscript ./unittest.R
